<a href="https://colab.research.google.com/github/shivani257/numpy/blob/main/NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import the libraries so we import pandas library
import pandas as pd

In [ ]:
# here we load the dataset
data = pd.read_csv('/content/Social_Network_Ads.csv')

In [ ]:
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

# 0 stands for not purchased
# 1 stands for purchased
# this is a classification problem
# first we need to seperate out independent variable and dependent variable
# target variable is purchased


# here age gender and estimated salary are independent variable

# here purchased is dependent variable

In [ ]:
# here we want values
X = data.iloc[:,1:4].values
X

array([['Male', 19, 19000],
       ['Male', 35, 20000],
       ['Female', 26, 43000],
       ...,
       ['Female', 50, 20000],
       ['Male', 36, 33000],
       ['Female', 49, 36000]], dtype=object)

In [ ]:
y = data.iloc[:,-1].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [ ]:
# geneder are in text data we want to convert it into numeric data in the form of 0 and 1
# because ML won't handle text data
# encode
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()


In [ ]:
X[:,0] = le.fit_transform(X[:,0])

In [ ]:
X

array([[1, 19, 19000],
       [1, 35, 20000],
       [0, 26, 43000],
       ...,
       [0, 50, 20000],
       [1, 36, 33000],
       [0, 49, 36000]], dtype=object)

# now here 1 stands for male and 0 stands for female

now we want to split the dataset into training and testing

In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
# train_test_split
X_train,X_test,y_train, y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
len(X_train)

320

In [ ]:
len(X_test)

80

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
model = GaussianNB()

In [ ]:
model.fit(X_train,y_train)

GaussianNB()

In [ ]:
model.predict(X_test)
# 1 for purchased and 0 for not purchased

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0])

In [ ]:
X_test
# 1 for male and 0 for female

array([[0, 54, 104000],
       [1, 46, 88000],
       [1, 24, 84000],
       [1, 21, 88000],
       [1, 18, 82000],
       [1, 39, 71000],
       [1, 28, 123000],
       [0, 38, 55000],
       [1, 33, 43000],
       [1, 38, 59000],
       [1, 29, 148000],
       [1, 38, 71000],
       [0, 18, 44000],
       [1, 47, 43000],
       [0, 35, 77000],
       [0, 46, 41000],
       [1, 35, 73000],
       [1, 47, 25000],
       [1, 34, 43000],
       [1, 19, 76000],
       [1, 32, 120000],
       [0, 26, 72000],
       [0, 48, 138000],
       [0, 38, 80000],
       [1, 38, 61000],
       [0, 37, 93000],
       [1, 19, 19000],
       [1, 25, 90000],
       [0, 27, 54000],
       [0, 32, 135000],
       [1, 49, 28000],
       [1, 41, 87000],
       [0, 26, 43000],
       [0, 20, 23000],
       [1, 27, 20000],
       [1, 48, 33000],
       [0, 55, 130000],
       [0, 18, 86000],
       [1, 59, 143000],
       [1, 34, 112000],
       [1, 31, 58000],
       [1, 54, 70000],
       [1, 42, 80000],
  

In [ ]:
model.score(X_test,y_test)

0.9