<a href="https://colab.research.google.com/github/shivani257/numpy/blob/main/Numpy_Assignment01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Assignment: np.zeros()**

In [2]:
import numpy as np


In [3]:
# 1D
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
# 2D syntax: np.zeros(rows,columns)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
#3D syntax: np.zeros(block,rows,columns)
np.zeros((3,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

# **Assignment: np.ones()**

In [6]:
# 1D
np.ones((5))

array([1., 1., 1., 1., 1.])

In [7]:
# 2D
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# 3D
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

# **Assignment: create a 3D array with random**


In [9]:
# 1D
np.random.random(5)

array([0.83340631, 0.1908482 , 0.51164195, 0.17241885, 0.06081418])

In [11]:
# 2D
np.random.random((3,4))

array([[0.78466786, 0.16015561, 0.53769835, 0.63916579],
       [0.12758118, 0.2588664 , 0.37179237, 0.51388342],
       [0.2045465 , 0.87157644, 0.29807213, 0.51971397]])

In [13]:
# 3D
np.random.random((3,3,4))

array([[[0.80487667, 0.29277853, 0.86460743, 0.91137046],
        [0.61185238, 0.00712403, 0.50964061, 0.20060267],
        [0.69568377, 0.89991469, 0.71539837, 0.95992182]],

       [[0.50955168, 0.97370323, 0.61273399, 0.65391552],
        [0.45736068, 0.5375772 , 0.71098973, 0.41844909],
        [0.04549537, 0.15134394, 0.63065356, 0.05862477]],

       [[0.5912787 , 0.65981028, 0.58384927, 0.77582387],
        [0.6230901 , 0.25639278, 0.67168731, 0.11528276],
        [0.78128024, 0.00489939, 0.46473927, 0.20634694]]])

# Identity matrix:

whose daigonal elements are 1 and non daigonal elements are 0**

In [14]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# **Assignment: np.eye()**
we can change the daigonal elements in np.eye()

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.eye(6,k=1)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
np.eye(5,k=1,dtype=int)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [22]:
np.eye(5,k=-1,dtype=int)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])