<a href="https://colab.research.google.com/github/shivani257/numpy/blob/main/numpyAssignment_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
a = np.random.random((4,4))
a

array([[0.04881579, 0.81134611, 0.15325413, 0.93854141],
       [0.9137405 , 0.5561551 , 0.14023319, 0.02735921],
       [0.38657536, 0.29092395, 0.69271128, 0.11807119],
       [0.73235014, 0.14158138, 0.89096885, 0.6969264 ]])

In [10]:
# add -1 in each column
#add -1 row
np.append(a,[[-1,-1,-1,-1]],axis=0)

array([[ 0.04881579,  0.81134611,  0.15325413,  0.93854141],
       [ 0.9137405 ,  0.5561551 ,  0.14023319,  0.02735921],
       [ 0.38657536,  0.29092395,  0.69271128,  0.11807119],
       [ 0.73235014,  0.14158138,  0.89096885,  0.6969264 ],
       [-1.        , -1.        , -1.        , -1.        ]])

## **Assignment : Add -2 in each row**

In [16]:
np.append(a,[[-2],[-2],[-2],[-2]],axis=1)

array([[ 0.04881579,  0.81134611,  0.15325413,  0.93854141, -2.        ],
       [ 0.9137405 ,  0.5561551 ,  0.14023319,  0.02735921, -2.        ],
       [ 0.38657536,  0.29092395,  0.69271128,  0.11807119, -2.        ],
       [ 0.73235014,  0.14158138,  0.89096885,  0.6969264 , -2.        ]])

In [18]:
np.append(a,np.full((4,1),-2),axis=1)

array([[ 0.04881579,  0.81134611,  0.15325413,  0.93854141, -2.        ],
       [ 0.9137405 ,  0.5561551 ,  0.14023319,  0.02735921, -2.        ],
       [ 0.38657536,  0.29092395,  0.69271128,  0.11807119, -2.        ],
       [ 0.73235014,  0.14158138,  0.89096885,  0.6969264 , -2.        ]])