<a href="https://colab.research.google.com/github/shivani257/numpy/blob/main/Numpy_Assignment02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
a = np.random.randn(4,5)
a

array([[ 0.31056217,  1.51948661, -0.4690507 , -0.17417057,  0.33795976],
       [ 0.85812998, -0.00735745,  0.24088297,  1.00235656,  0.01665591],
       [-0.27329753,  0.26966697, -0.37573303,  1.25179675,  0.7016582 ],
       [ 0.47339641,  0.4259929 ,  0.75288022, -1.24146997,  1.58865245]])

In [8]:
#1st and 3rd row
a[0::2]

array([[ 0.31056217,  1.51948661, -0.4690507 , -0.17417057,  0.33795976],
       [-0.27329753,  0.26966697, -0.37573303,  1.25179675,  0.7016582 ]])

In [9]:
# 2nd and 4th row
a[1::2]

array([[ 0.85812998, -0.00735745,  0.24088297,  1.00235656,  0.01665591],
       [ 0.47339641,  0.4259929 ,  0.75288022, -1.24146997,  1.58865245]])

# Assignment

# Access last 2 rows


In [10]:
a

array([[ 0.31056217,  1.51948661, -0.4690507 , -0.17417057,  0.33795976],
       [ 0.85812998, -0.00735745,  0.24088297,  1.00235656,  0.01665591],
       [-0.27329753,  0.26966697, -0.37573303,  1.25179675,  0.7016582 ],
       [ 0.47339641,  0.4259929 ,  0.75288022, -1.24146997,  1.58865245]])

In [13]:
a[-2:]

array([[-0.27329753,  0.26966697, -0.37573303,  1.25179675,  0.7016582 ],
       [ 0.47339641,  0.4259929 ,  0.75288022, -1.24146997,  1.58865245]])

# Access middle 2 rows

In [14]:
a[1:3]

array([[ 0.85812998, -0.00735745,  0.24088297,  1.00235656,  0.01665591],
       [-0.27329753,  0.26966697, -0.37573303,  1.25179675,  0.7016582 ]])

In [18]:
a[-3:-1]

array([[ 0.85812998, -0.00735745,  0.24088297,  1.00235656,  0.01665591],
       [-0.27329753,  0.26966697, -0.37573303,  1.25179675,  0.7016582 ]])

# Access 1st and last row

In [20]:
a

array([[ 0.31056217,  1.51948661, -0.4690507 , -0.17417057,  0.33795976],
       [ 0.85812998, -0.00735745,  0.24088297,  1.00235656,  0.01665591],
       [-0.27329753,  0.26966697, -0.37573303,  1.25179675,  0.7016582 ],
       [ 0.47339641,  0.4259929 ,  0.75288022, -1.24146997,  1.58865245]])

In [24]:
a[::3]

array([[ 0.31056217,  1.51948661, -0.4690507 , -0.17417057,  0.33795976],
       [ 0.47339641,  0.4259929 ,  0.75288022, -1.24146997,  1.58865245]])

# Access 2nd and last row

In [26]:
a[1::2]

array([[ 0.85812998, -0.00735745,  0.24088297,  1.00235656,  0.01665591],
       [ 0.47339641,  0.4259929 ,  0.75288022, -1.24146997,  1.58865245]])

In [27]:
a[-3::2]

array([[ 0.85812998, -0.00735745,  0.24088297,  1.00235656,  0.01665591],
       [ 0.47339641,  0.4259929 ,  0.75288022, -1.24146997,  1.58865245]])

# Access last 3 rows

In [28]:
a

array([[ 0.31056217,  1.51948661, -0.4690507 , -0.17417057,  0.33795976],
       [ 0.85812998, -0.00735745,  0.24088297,  1.00235656,  0.01665591],
       [-0.27329753,  0.26966697, -0.37573303,  1.25179675,  0.7016582 ],
       [ 0.47339641,  0.4259929 ,  0.75288022, -1.24146997,  1.58865245]])

In [30]:
a[-3:]

array([[ 0.85812998, -0.00735745,  0.24088297,  1.00235656,  0.01665591],
       [-0.27329753,  0.26966697, -0.37573303,  1.25179675,  0.7016582 ],
       [ 0.47339641,  0.4259929 ,  0.75288022, -1.24146997,  1.58865245]])

In [32]:
a[1:]

array([[ 0.85812998, -0.00735745,  0.24088297,  1.00235656,  0.01665591],
       [-0.27329753,  0.26966697, -0.37573303,  1.25179675,  0.7016582 ],
       [ 0.47339641,  0.4259929 ,  0.75288022, -1.24146997,  1.58865245]])

# **Assignment**

# Access corner elements

In [48]:
a = np.random.randn(4,4)
a

array([[ 0.0843226 , -1.19498467, -0.30364749, -0.72296333],
       [ 1.60157601, -0.04590945,  2.22176268, -1.42038673],
       [-1.49866146,  0.31886461,  1.7897804 , -0.14765192],
       [ 1.41409456, -0.66926148,  0.17309492,  0.3407506 ]])

In [52]:
a[::3,::3]

array([[ 0.0843226 , -0.72296333],
       [ 1.41409456,  0.3407506 ]])

# Access daigonal elements

In [53]:
np.diagonal(a)

array([ 0.0843226 , -0.04590945,  1.7897804 ,  0.3407506 ])

# Access middle 2 columns and all rows

In [54]:
a[:,1:3]

array([[-1.19498467, -0.30364749],
       [-0.04590945,  2.22176268],
       [ 0.31886461,  1.7897804 ],
       [-0.66926148,  0.17309492]])

# Access last 2 rows and its first 2 values from each row

In [55]:
a

array([[ 0.0843226 , -1.19498467, -0.30364749, -0.72296333],
       [ 1.60157601, -0.04590945,  2.22176268, -1.42038673],
       [-1.49866146,  0.31886461,  1.7897804 , -0.14765192],
       [ 1.41409456, -0.66926148,  0.17309492,  0.3407506 ]])

In [60]:
a[-2:,0:1]

array([[-1.49866146],
       [ 1.41409456]])

# Reverse rows and column as well

In [58]:
a[::-1,::-1]

array([[ 0.3407506 ,  0.17309492, -0.66926148,  1.41409456],
       [-0.14765192,  1.7897804 ,  0.31886461, -1.49866146],
       [-1.42038673,  2.22176268, -0.04590945,  1.60157601],
       [-0.72296333, -0.30364749, -1.19498467,  0.0843226 ]])